# Att: https://github.com/C4TDOGDevelop
# Se recomienda borrar el archivo original y poner este.
header-footer:
  enabled: true
  header:
    - ""
    - "&#FB0000s&#FB0B0Bᴇ&#FC1717ʀ&#FC2222ᴠ&#FC2D2Dᴇ&#FD3939ʀ&#FD4444ɴ&#FD4F4Fᴀ&#FE5B5Bᴍ&#FE6666ᴇ"
    - ""
    - "&f¡Comparte nuestra IP a tus amigos!"
    - "&#FB0000s&#FB0B0Bᴇ&#FC1717ʀ&#FC2222ᴠ&#FC2D2Dᴇ&#FD3939ʀ&#FD4444ɴ&#FD4F4Fᴀ&#FE5B5Bᴍ&#FE6666ᴇ"
    - ""
  footer:
    - ""
    - "&3⚓ &fDiviertete jugando en nuestro &bservidor &3₪"
    - "&7Unete a la comunidad: &ddiscord.gg"
    - ""
    - "&f¡Compra &erangos&f, &cbeneficios&f y más!"
    - "&#FB0000s&#FB0B0Bᴇ&#FC1717ʀ&#FC2222ᴠ&#FC2D2Dᴇ&#FD3939ʀ&#FD4444ɴ&#FD4F4Fᴀ&#FE5B5Bᴍ&#FE6666ᴇ"
  disable-condition: '%world%=disabledworld'
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
  per-server:
    server1:
      header:
      - an example of server with custom header
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-condition: '%world%=disabledworld'
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld'
  unlimited-nametag-mode:
    enabled: false
    disable-on-boats: true
    disable-condition: '%world%=disabledworld'
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
playerlist-objective:
  enabled: true
  value: '%ping%'
  fancy-value: '&7Ping: %ping%'
  disable-condition: '%world%=disabledworld'
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&cHealth'
  fancy-display-players: '&c%health%'
  fancy-display-default: NPC
  disable-condition: '%world%=disabledworld'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: true
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fAtt: &#08E7FB@&#17E4FBz&#26E1FBB&#35DEFCl&#44DBFCa&#53D8FCc&#62D5FCk&#71D2FCD&#80CFFCe&#8FCCFDm&#9EC9FDo&#ADC6FDn'
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    scoreboard:
      title: '&#FB0000s&#FB0B0Bᴇ&#FC1717ʀ&#FC2222ᴠ&#FC2D2Dᴇ&#FD3939ʀ&#FD4444ɴ&#FD4F4Fᴀ&#FE5B5Bᴍ&#FE6666ᴇ'
      lines:
       - '  &7⌚ %localtime_time%'
       - ''
       - ' &fNombre: &a%player_name%'
       - ' &fRango: %changeoutput_equals_input:default_matcher:{vault_rank}_ifmatch:&c¡Adquierelo!_else:{vault_prefix}%'
       - ''
       - ' &x&0&8&E&7&F&B🪣 &fCajas: &x&0&8&E&7&F&B0'
       - ' &7🌧 &fPolvos: &70'
       - ' &x&0&8&E&7&F&B✈ &fCabezas: &x&0&8&E&7&F&B0/20'
       - ''
       - ' &fLobby: &x&0&8&E&7&F&B#1'
       - ' &fConectados: &a%bungee_total%'
       - ''
       - '   &#FB0000s&#FB0B0Bᴇ&#FC1717ʀ&#FC2222ᴠ&#FC2D2Dᴇ&#FD3939ʀ&#FD4444ɴ&#FD4F4Fᴀ&#FE5B5Bᴍ&#FE6666ᴇ'
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      fixed-slots:
      - '1|&3Website&f:'
      - 2|&bmyserver.net
      - '3|&8&m                       '
      - '4|&3Name&f:'
      - 5|&b%player%
      - '7|&3Rank&f:'
      - '8|Rank: %group%'
      - '10|&3World&f:'
      - 11|&b%world%
      - '13|&3Time&f:'
      - 14|&b%time%
      - '21|&3Teamspeak&f:'
      - 22|&bts.myserver.net
      - '23|&8&m                       '
      - '41|&3Store&f:'
      - 42|&bshop.myserver.net
      - '43|&8&m                       '
      groups:
        staff:
          condition: permission:tab.staff
          slots:
          - 24-40
        players:
          slots:
          - 44-80
ping-spoof:
  enabled: false
  value: 0
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- Admin
- Mod
- Helper
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  spy-servers:
  - spyserver1
  - spyserver2
  server-groups:
    lobbies:
    - lobby1
    - lobby2
    group2:
    - server1
    - server2
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true
